/* Brand workspace. Notion is an immutable source; every write is confined to Google Sheets. */
const BCRM={brands:'브랜드 운영정보',archive:'노션 영업자료',notes:'브랜드 영업기록',attachments:'노션 첨부 이관'};
let CRM_READ_SCOPE_=null;
function crmReadScope_(fn){assertAdmin_();if(CRM_READ_SCOPE_)return fn();CRM_READ_SCOPE_={rows:{},products:null};try{return fn()}finally{CRM_READ_SCOPE_=null}}
function crmRows_(name){if(CRM_READ_SCOPE_&&Object.prototype.hasOwnProperty.call(CRM_READ_SCOPE_.rows,name))return CRM_READ_SCOPE_.rows[name];const s=getDb_().getSheetByName(name);if(!s)return [];const v=s.getDataRange().getDisplayValues(),h=v.shift()||[];const rows=v.map((r,i)=>{const o={_row:i+2};h.forEach((k,j)=>{if(k)o[k]=r[j]||''});return o}).filter(o=>Object.keys(o).some(k=>k!=='_row'&&o[k]));if(CRM_READ_SCOPE_)CRM_READ_SCOPE_.rows[name]=rows;return rows;}
function crmAllProducts_(){if(!CRM_READ_SCOPE_)return listProducts_({});if(!CRM_READ_SCOPE_.products)CRM_READ_SCOPE_.products=listProducts_({});return CRM_READ_SCOPE_.products;}
function crmJson_(v){try{return JSON.parse(v||'{}')}catch(e){return {}}}
function crmText_(v){if(Array.isArray(v))return v.join(', ');const s=String(v==null?'':v);if(s.charAt(0)==='['){try{const a=JSON.parse(s);if(Array.isArray(a))return a.join(', ')}catch(e){}}return s.replace(/<br\s*\/?>/gi,'\n').replace(/\\([\[\]])/g,'$1');}
function crmDate_(v){const s=String(v||'').trim();if(!s)return '';if(/^\d{5}(\.\d+)?$/.test(s))return Utilities.formatDate(new Date((Number(s)-25569)*86400000),'GMT','yyyy-MM-dd');return s.slice(0,10);}
function crmId_(url){const m=String(url||'').replace(/-/g,'').match(/[a-f0-9]{32}/i);return m?m[0]:'';}
function crmSafeCell_(v){const s=String(v==null?'':v);return /^[=+@-]/.test(s)?"'"+s:s;}
function crmWriteRow_(sheet,row,object){const h=sheet.getRange(1,1,1,sheet.getLastColumn()).getDisplayValues()[0];sheet.getRange(row,1,1,h.length).setValues([h.map(k=>crmSafeCell_(object[k]===undefined?'':object[k]))]);}
function crmProducts_(){return crmAllProducts_().filter(p=>p.status!=='중지');}
function crmBrand_(r){return {brandCode:r['브랜드ID'],brandName:r['브랜드명'],companyName:r['회사명'],salesStage:r['영업단계'],reStage:r['재영업단계'],reGroup:r['재영업분류'],priority:r['우선순위'],owner:r['사내담당자'],ownerId:r['담당자ID'],contact:r['브랜드담당자'],phone:r['연락처'],email:r['이메일'],category:crmText_(r['카테고리']),trade:crmText_(r['거래방식']),channels:crmText_(r['희망채널']),memo:r['핵심메모'],nextAction:r['다음행동'],nextDate:crmDate_(r['다음연락일']),lastContact:crmDate_(r['최근연락일']),reference:r['참고자료'],drive:r['Drive주소'],status:r['상태'],version:String(r['버전']||'0'),sourceUrl:r['원본URL'],updatedAt:r['수정일'],features:r['상품특장점'],productGroup:r['대표상품군']};}
function crmAllBrands_(){const rows=crmRows_(BCRM.brands).slice(),ids={};rows.forEach(r=>ids[r['브랜드ID']]=true);crmRows_(BOPS.SHEETS.BRANDS).forEach(r=>{const id=r['브랜드 ID'];if(id&&!ids[id])rows.push({'브랜드ID':id,'브랜드명':r['브랜드명'],'회사명':r['협력사/회사명'],'영업단계':r['진행 단계'],'브랜드담당자':r['브랜드 담당자'],'연락처':r['연락처'],'이메일':r['이메일'],'카테고리':r['카테고리'],'다음행동':r['다음 행동'],'핵심메모':r['핵심 메모'],'참고자료':r['참고 링크/자료'],'원본URL':r['Notion URL'],'상태':'활성','버전':'0'})});return rows.filter(r=>r['브랜드ID']&&r['상태']!=='삭제');}
function crmActivity_(brandId,archive,notes){const imported=archive.filter(r=>r['브랜드ID']===brandId&&r['구분']==='연락 이력').map(r=>{const p=crmJson_(r['속성JSON']);return {id:r['자료ID'],date:crmDate_(p['date:일자:start']),method:p['연락 방식']||'기록',result:p['결과']||'',owner:crmText_(p['상담 담당자']||''),contact:p['상대방 담당자']||'',content:crmText_(p['통화 내용']||''),nextAction:crmText_(p['다음 행동']||''),due:crmDate_(p['date:후속 확인일:start']),complete:p['후속 완료']==='__YES__',source:'노션 이관',title:r['제목'],body:r['본문'],url:r['원본URL']}});
const local=notes.filter(r=>r['브랜드ID']===brandId).map(r=>({id:r['기록ID'],date:r['활동일'],method:r['연락방식'],result:r['결과'],owner:r['담당자'],contact:r['상대담당자'],content:r['내용'],nextAction:r['다음행동'],due:r['후속일'],complete:r['완료']==='TRUE',created:r['작성일'],source:'운영센터'}));return local.reverse().concat(imported.sort((a,b)=>String(b.date).localeCompare(String(a.date))));}
function crmWorkspaceBase_(){assertAdmin_();const products=crmProducts_(),archive=crmRows_(BCRM.archive),notes=crmRows_(BCRM.notes),sub=crmRows_(BOPS.SHEETS.SUBMISSIONS);const rows=crmAllBrands_().map(r=>{const b=crmBrand_(r),pp=products.filter(p=>p.brandCode===b.brandCode),aa=crmActivity_(b.brandCode,archive,notes);b.productCount=pp.length;b.reviewCount=sub.filter(s=>s['브랜드코드']===b.brandCode&&/신규|검수|제출/.test(s['상태'])).length;b.revisionCount=sub.filter(s=>s['브랜드코드']===b.brandCode&&/보완/.test(s['상태'])).length;b.activityCount=aa.length;b.pendingTasks=aa.filter(a=>a.source==='운영센터'&&a.nextAction&&!a.complete).map(a=>({task:a.nextAction,date:a.due}));b.archived=archive.some(a=>a['브랜드ID']===b.brandCode&&a['구분']==='브랜드 본문');const recent=aa.find(a=>a.source==='운영센터'&&a.nextAction&&!a.complete);if(recent){b.nextAction=recent.nextAction;b.nextDate=recent.due}b.recent=aa[0]?{text:aa[0].content||aa[0].title||aa[0].result,date:aa[0].date}:null;const dates=aa.map(a=>a.date).filter(Boolean).sort();if(dates.length)b.lastContact=dates[dates.length-1];return b});return {rows:rows.sort((a,b)=>a.brandCode.localeCompare(b.brandCode)),today:dateOnly_(),user:getCurrentUser_(),archiveCount:archive.length};}
function crmDetailBase_(code){assertAdmin_();code=String(code||'');const row=crmAllBrands_().find(r=>r['브랜드ID']===code);if(!row)throw Error('브랜드를 찾을 수 없습니다.');const b=crmBrand_(row),archive=crmRows_(BCRM.archive).filter(r=>r['브랜드ID']===code),products=crmProducts_().filter(p=>p.brandCode===code),productIds={};products.forEach(p=>productIds[p.productId]=p.productName);return {brand:b,activities:crmActivity_(code,archive,crmRows_(BCRM.notes)),archive:archive.map(r=>({id:r['자료ID'],type:r['구분'],title:r['제목'],url:r['원본URL'],body:r['본문'],properties:crmJson_(r['속성JSON']),importedAt:r['이관일']})),products:products.map(p=>({id:p.productId,name:crmText_(p.productName),option:p.optionName,barcode:p.barcode,price:p.retailPrice,status:p.reviewStatus||p.status||'자료 수집',category:p.category,trade:p.tradeType})),conditions:crmRows_('가격·공급조건').filter(r=>productIds[r['상품ID']]).map(r=>Object.assign({},r,{'상품명':productIds[r['상품ID']]})),files:crmRows_(BCRM.attachments).filter(r=>r['브랜드ID']===code),link:listBrands_({query:code}).find(x=>x.brandCode===code)?.link||null};}
function crmValidateDate_(s){if(s&&!/^\d{4}-\d{2}-\d{2}$/.test(s))throw Error('날짜 형식을 확인해 주세요.');if(s){const d=new Date(s+'T00:00:00Z');if(isNaN(d)||d.toISOString().slice(0,10)!==s)throw Error('유효한 날짜를 입력해 주세요.');}return s;}
function crmPatchBase_(payload){const map={brandName:'브랜드명',companyName:'회사명',salesStage:'영업단계',reStage:'재영업단계',priority:'우선순위',owner:'사내담당자',contact:'브랜드담당자',phone:'연락처',email:'이메일',category:'카테고리',trade:'거래방식',channels:'희망채널',memo:'핵심메모',nextAction:'다음행동',nextDate:'다음연락일',reference:'참고자료'};const patch={};Object.keys(map).forEach(k=>{if(Object.prototype.hasOwnProperty.call(payload,k)){const s=String(payload[k]??'').trim();if(s.length>12000)throw Error('입력 내용이 너무 깁니다: '+map[k]);patch[map[k]]=s;}});if('브랜드명'in patch&&!patch['브랜드명'])throw Error('브랜드명은 필수입니다.');if('다음연락일'in patch)crmValidateDate_(patch['다음연락일']);return patch;}
function saveBrandProfile(payload){assertAdmin_();return withLock_(function(){const rows=crmAllBrands_(),r=rows.find(x=>x['브랜드ID']===payload.brandCode);if(!r)throw Error('브랜드를 찾을 수 없습니다.');if(String(r['버전']||'0')!==String(payload.version))throw Error('다른 사용자가 먼저 수정했습니다. 상세를 다시 열고 변경사항을 확인해 주세요.');const patch=crmPatch_(payload),keys=Object.keys(patch),changed=keys.some(k=>String(r[k]||'')!==patch[k]);if(!changed)return {ok:true,changed:false};Object.assign(r,patch,{'수정일':now_(),'수정자':getActiveUserEmail_(),'버전':String(Number(r['버전']||0)+1)});const sh=getSheet_(BCRM.brands);crmWriteRow_(sh,r._row||sh.getLastRow()+1,r);logAction_('브랜드 수정','브랜드',payload.brandCode,keys.join(', '));return {ok:true,changed:true};});}
function addBrandActivity(payload){assertAdmin_();return withLock_(function(){payload=payload||{};const code=String(payload.brandCode||''),request=String(payload.requestId||'');if(!/^[a-zA-Z0-9-]{8,100}$/.test(request))throw Error('저장 요청ID가 올바르지 않습니다.');const exists=crmRows_(BCRM.notes).find(r=>r['요청ID']===request);if(exists){if(exists['브랜드ID']!==code)throw Error('요청ID 충돌');return {ok:true,id:exists['기록ID'],duplicate:true}}if(!crmAllBrands_().some(r=>r['브랜드ID']===code))throw Error('브랜드를 찾을 수 없습니다.');const content=String(payload.content||'').trim();if(!content||content.length>12000)throw Error('상담 내용을 1~12,000자로 입력해 주세요.');const date=crmValidateDate_(String(payload.date||'')),due=crmValidateDate_(String(payload.due||''));if(!date)throw Error('활동일을 입력해 주세요.');if(!['전화','이메일','미팅','메신저','기타'].includes(payload.method))throw Error('연락 방식을 선택해 주세요.');const id=uuid_('ACT-'),sh=getSheet_(BCRM.notes);crmWriteRow_(sh,sh.getLastRow()+1,{'기록ID':id,'브랜드ID':code,'활동일':date,'연락방식':payload.method,'결과':String(payload.result||'').slice(0,100),'담당자':getActiveUserEmail_(),'상대담당자':String(payload.contact||'').slice(0,200),'내용':content,'다음행동':String(payload.nextAction||'').slice(0,12000),'후속일':due,'완료':'FALSE','작성일':now_(),'요청ID':request});return {ok:true,id:id};});}
function completeBrandActivity(payload){assertAdmin_();return withLock_(function(){const row=crmRows_(BCRM.notes).find(r=>r['기록ID']===payload.id&&r['브랜드ID']===payload.brandCode);if(!row)throw Error('운영센터에서 작성한 기록만 완료 처리할 수 있습니다.');row['완료']='TRUE';crmWriteRow_(getSheet_(BCRM.notes),row._row,row);return {ok:true};});}
function migrateBrandImages(){assertAdmin_();const rows=crmRows_(BCRM.attachments).filter(r=>r['상태']!=='보관 완료'&&/^https:\/\/(?:prod-files-secure\.s3\.us-west-2\.amazonaws\.com|file\.notion\.com)\//.test(r['원본주소']));if(!rows.length){console.log('추가 이관 이미지 없음');return;}const props=PropertiesService.getScriptProperties();let folderId=props.getProperty('BCRM_ARCHIVE_FOLDER');if(!folderId){const parents=DriveApp.getFileById(getDb_().getId()).getParents();const folder=(parents.hasNext()?parents.next():DriveApp.getRootFolder()).createFolder('뷰티오라 노션 영업자료 보관');folderId=folder.getId();props.setProperty('BCRM_ARCHIVE_FOLDER',folderId)}const folder=DriveApp.getFolderById(folderId),sheet=getSheet_(BCRM.attachments);let ok=0;rows.forEach(r=>{try{const name=r['첨부ID']+'-'+r['파일명'];const existing=folder.getFilesByName(name);let file;if(existing.hasNext())file=existing.next();else{const response=UrlFetchApp.fetch(r['원본주소'],{muteHttpExceptions:true,followRedirects:true});if(response.getResponseCode()!==200)throw Error('원본 응답 '+response.getResponseCode());const blob=response.getBlob();if(!/^(image\/|application\/pdf)/.test(blob.getContentType()))throw Error('이미지 형식 확인 필요');file=folder.createFile(blob.setName(name))}r['Drive주소']=file.getUrl();r['상태']='보관 완료';r['오류']='';r['이관일']=now_();ok++;}catch(e){r['상태']='확인 필요';r['오류']=String(e.message).slice(0,300)}crmWriteRow_(sheet,r._row,r)});console.log(JSON.stringify({images:rows.length,saved:ok}));}
function testBrandWorkspace(){assertAdmin_();let tests=0;function check(b,msg){if(!b)throw Error(msg);tests++}const w=getBrandWorkspace();check(w.rows.length===107,'브랜드 수');check(new Set(w.rows.map(b=>b.brandCode)).size===107,'중복 브랜드');check(w.rows.every(b=>b.archived),'본문 누락');check(w.rows.filter(b=>b.owner).length===3,'담당자 연결');check(w.rows.some(b=>b.productCount>0),'상품 집계');const d=getBrandDetail('BO-0009');check(d.archive.some(a=>a.body.includes('수수료나 입점비')),'본문 상담메모');check(crmText_('["사입","위탁"]')==='사입, 위탁','배열 표시');check(crmSafeCell_('=IMPORTXML(x)')[0]==="'",'수식 방지');let invalid=false;try{crmValidateDate_('2026-02-31')}catch(e){invalid=true}check(invalid,'날짜 검증');check(Object.keys(crmPatch_({sourceUrl:'bad',version:99})).length===0,'허용 필드');check(d.activities.every(a=>a.source==='노션 이관'||a.source==='운영센터'),'이력 출처');console.log(JSON.stringify({passed:tests,brands:w.rows.length,products:w.rows.reduce((s,b)=>s+b.productCount,0),archives:w.archiveCount,notionWrites:0}));}

const CRM_STAGES=['전환 확인 전','재연락','회신 대기','상품 검토','샘플 검토','조건 협의','매입 진행 확정','보류','진행 불가'];
const CRM_SAMPLES=['미등록','요청 예정','요청 완료','수령 완료','검토 완료','불필요'];
function crmEnhance_(b,r){Object.assign(b,{workflow:r['매입전환상태']||'전환 확인 전',contactPriority:r['전환연락순위']||(/^[12]순위/.test(b.reGroup)?b.reGroup.slice(0,3):'3순위'),task:r['현재다음업무']||'',taskDate:crmDate_(r['현재업무예정일']),sample:r['샘플상태']||'미등록',reviewMemo:r['매입검토메모']||'',logo:r['로고URL']||''});return b;}
function crmInventory_(){const products=crmAllProducts_(),map={};products.forEach(p=>map[p.productId]=p);const places={};crmRows_('장소').forEach(r=>places[r['장소ID']]=r['장소명']);return crmRows_('현재고').map(r=>({brandCode:map[r['상품ID']]?.brandCode||'',productId:r['상품ID'],name:crmText_(r['상품명']),place:places[r['장소ID']]||r['장소ID'],placeId:r['장소ID'],purchase:Number(r['매입재고'])||0,consignment:Number(r['위탁재고'])||0,unknown:Number(r['미분류재고'])||0,sample:Number(r['샘플DP'])||0,available:r['가용재고'],updated:r['최종수정']}));}
function getBrandWorkspace(){return crmReadScope_(crmWorkspaceRead_);}
function crmWorkspaceRead_(){
  assertAdmin_();
  const products=crmProducts_(),archive=crmRows_(BCRM.archive),notes=crmRows_(BCRM.notes),sub=crmRows_(BOPS.SHEETS.SUBMISSIONS),brands=crmAllBrands_();
  const byBrand=(rows,key)=>rows.reduce((map,row)=>{const id=String(row[key]||'');(map[id]||(map[id]=[])).push(row);return map;},{});
  const productByBrand=products.reduce((map,p)=>{(map[p.brandCode]||(map[p.brandCode]=[])).push(p);return map;},{});
  const archiveByBrand=byBrand(archive,'브랜드ID'),notesByBrand=byBrand(notes,'브랜드ID'),subByBrand=byBrand(sub,'브랜드코드');
  const productBrand={};products.forEach(p=>productBrand[p.productId]=p.brandCode);
  const stockByBrand={};let inventoryUpdated='';
  crmRows_('현재고').forEach(r=>{
    const code=productBrand[r['상품ID']]||'';if(!code)return;
    const s=stockByBrand[code]||(stockByBrand[code]={purchase:0,consignment:0,unknown:0,sample:0});
    s.purchase+=Number(r['매입재고'])||0;s.consignment+=Number(r['위탁재고'])||0;s.unknown+=Number(r['미분류재고'])||0;s.sample+=Number(r['샘플DP'])||0;
    if(r['최종수정']&&String(r['최종수정'])>inventoryUpdated)inventoryUpdated=String(r['최종수정']);
  });
  const staffFiles=crmRows_(BOPS.SHEETS.FILES);opsJournal_().forEach(r=>{const code=r['브랜드코드'],s=stockByBrand[code]||(stockByBrand[code]={purchase:0,consignment:0,unknown:0,sample:0});const k={'매입':'purchase','위탁':'consignment','미분류':'unknown'}[r['거래방식']]||'unknown';s[k]+=(r['구분']==='입고'?1:-1)*Number(r['수량']);});
  const rows=brands.map(r=>{
    const b=crmBrand_(r),code=b.brandCode,pp=productByBrand[code]||[],aa=crmActivity_(code,archiveByBrand[code]||[],notesByBrand[code]||[]),ss=subByBrand[code]||[];
    b.fileCount=staffFiles.filter(f=>f['브랜드코드']===code).length;b.barcodeMissing=pp.filter(p=>!p.barcode).length;b.productCount=pp.length;b.reviewCount=ss.filter(s=>/신규|검수|제출/.test(s['상태'])).length;b.revisionCount=ss.filter(s=>/보완/.test(s['상태'])).length;b.activityCount=aa.length;
    b.pendingTasks=aa.filter(a=>a.source==='운영센터'&&a.nextAction&&!a.complete).map(a=>({task:a.nextAction,date:a.due}));
    b.archived=(archiveByBrand[code]||[]).some(a=>a['구분']==='브랜드 본문');
    const recent=aa.find(a=>a.source==='운영센터'&&a.nextAction&&!a.complete);if(recent){b.nextAction=recent.nextAction;b.nextDate=recent.due;}
    b.recent=aa[0]?{text:aa[0].content||aa[0].title||aa[0].result,date:aa[0].date}:null;
    const dates=aa.map(a=>a.date).filter(Boolean).sort();if(dates.length)b.lastContact=dates[dates.length-1];
    crmEnhance_(b,r);
    const tasks=(b.task?[{task:b.task,date:b.taskDate}]:[]).concat(b.pendingTasks||[]).sort((a,c)=>(a.date||'9999').localeCompare(c.date||'9999'));if(tasks.length){b.task=tasks[0].task;b.taskDate=tasks[0].date;}
    b.stock=stockByBrand[code]||{purchase:0,consignment:0,unknown:0,sample:0};
    const cover=pp.find(p=>p.mainImageUrl);b.cover=cover?cover.mainImageUrl:'';
    return b;
  }).sort((a,b)=>a.brandCode.localeCompare(b.brandCode));
  return {rows,today:dateOnly_(),user:getCurrentUser_(),archiveCount:archive.length,stages:CRM_STAGES,inventoryUpdated};
}
function getBrandDetail(code){return crmReadScope_(()=>crmDetailRead_(code));}
function crmDetailRead_(code){assertAdmin_();const d=crmDetailBase_(code),r=crmAllBrands_().find(r=>r['브랜드ID']===code)||{};crmEnhance_(d.brand,r);const pp=crmProducts_().filter(p=>p.brandCode===code);d.products.forEach(p=>{const full=pp.find(x=>x.productId===p.id);p.image=full?.mainImageUrl||'';p.url=full?.productUrl||full?.detailPageUrl||'';p.purchase=full?.purchasePrice||'';});d.stock=opsStock_(code);d.submitted=opsSources_(code);d.issues=opsRows_('자료 확인사항').filter(r=>r['브랜드코드']===code&&r['상태']!=='완료');d.files=d.files.concat(opsFiles_(code));const ids={};crmAllProducts_().filter(p=>p.brandCode===code).forEach(p=>ids[p.productId]=true);d.movements=crmRows_('재고거래').filter(r=>ids[r['상품ID']]);d.terms=crmRows_('거래조건 관리').filter(r=>r['브랜드ID']===code).reverse();d.stages=CRM_STAGES;d.samples=CRM_SAMPLES;return d;}
function crmPatch_(p){const patch=crmPatchBase_(p),map={workflow:'매입전환상태',contactPriority:'전환연락순위',task:'현재다음업무',taskDate:'현재업무예정일',sample:'샘플상태',reviewMemo:'매입검토메모',logo:'로고URL',drive:'Drive주소'};Object.keys(map).forEach(k=>{if(Object.prototype.hasOwnProperty.call(p,k)){const v=String(p[k]??'').trim();if(v.length>12000)throw Error('입력 내용이 너무 깁니다.');patch[map[k]]=v;}});if('workflow'in p&&!CRM_STAGES.includes(p.workflow))throw Error('매입 전환 상태를 선택해 주세요.');if('sample'in p&&!CRM_SAMPLES.includes(p.sample))throw Error('샘플 상태를 선택해 주세요.');if('contactPriority'in p&&!['1순위','2순위','3순위'].includes(p.contactPriority))throw Error('연락 순위를 선택해 주세요.');if('taskDate'in p)crmValidateDate_(p.taskDate);if(p.logo&&!/^https:\/\//i.test(p.logo))throw Error('로고는 https 이미지 주소를 입력해 주세요.');return patch;}
function crmTermPatch_(p){if(!['매입','위탁'].includes(p.trade))throw Error('거래방식을 선택해 주세요.');if(!['제안','협의 중','확정','종료'].includes(p.state))throw Error('조건 상태를 선택해 주세요.');const map={trade:'거래방식',state:'조건상태',price:'공급가',retail:'소비자가',moq:'MOQ',pack:'박스입수',lead:'납기일수',payment:'결제조건',tax:'부가세',start:'적용시작일',end:'적용종료일',channel:'채널',memo:'메모'},out={};Object.keys(map).forEach(k=>{const v=String(p[k]??'').trim();if(v.length>4000)throw Error('입력 내용이 너무 깁니다.');out[map[k]]=v;});['price','retail','moq','pack','lead'].forEach(k=>{const v=String(p[k]??'').replace(/,/g,'').trim();if(v&&(!/^\d+(\.\d+)?$/.test(v)||!isFinite(Number(v))||Number(v)<0))throw Error('금액과 수량은 0 이상의 숫자로 입력해 주세요.');if(['moq','pack','lead'].includes(k)&&v&&!Number.isInteger(Number(v)))throw Error('수량과 납기는 정수로 입력해 주세요.');out[map[k]]=v;});crmValidateDate_(out['적용시작일']);crmValidateDate_(out['적용종료일']);if(out['적용시작일']&&out['적용종료일']&&out['적용종료일']<out['적용시작일'])throw Error('종료일은 시작일 이후여야 합니다.');if(p.state==='확정'&&(!out['공급가']||Number(out['공급가'])<=0||!out['MOQ']||Number(out['MOQ'])<1||!out['결제조건']||!out['적용시작일']||!['포함','별도','면세'].includes(p.tax)))throw Error('확정 시 공급가·MOQ·결제조건·부가세·적용 시작일을 입력해 주세요.');return out;}
function saveBrandTerms(p){assertAdmin_();return withLock_(function(){if(!p||!crmAllBrands_().some(b=>b['브랜드ID']===p.brandCode))throw Error('브랜드를 찾을 수 없습니다.');if(!crmAllProducts_().some(x=>x.brandCode===p.brandCode&&x.productId===p.productId))throw Error('브랜드에 속한 상품을 선택해 주세요.');if(!/^[a-zA-Z0-9-]{8,100}$/.test(p.requestId||''))throw Error('요청ID를 확인해 주세요.');const all=crmRows_('거래조건 관리'),old=all.find(r=>r['조건ID']===p.id),duplicate=all.find(r=>r['요청ID']===p.requestId);if(duplicate){if(duplicate['브랜드ID']!==p.brandCode)throw Error('요청ID 충돌');return {ok:true,duplicate:true};}if(p.id&&!old)throw Error('조건을 찾을 수 없습니다.');if(old&&(old['브랜드ID']!==p.brandCode||String(old['버전'])!==String(p.version)))throw Error('조건이 변경되었습니다. 다시 열어 확인해 주세요.');const patch=crmTermPatch_(p),r=Object.assign({},old||{},patch,{'조건ID':old?.['조건ID']||uuid_('TERM-'),'브랜드ID':p.brandCode,'상품ID':p.productId,'버전':String(Number(old?.['버전']||0)+1),'수정일':now_(),'수정자':getActiveUserEmail_(),'요청ID':p.requestId});const sh=getSheet_('거래조건 관리');crmWriteRow_(sh,old?old._row:sh.getLastRow()+1,r);logAction_('거래조건 저장','브랜드',p.brandCode,r['조건ID']+' · '+p.trade+' · '+p.state);return {ok:true};});}
function testBrandCommerce(){assertAdmin_();let passed=0;function check(x,m){if(!x)throw Error(m);passed++}const w=getBrandWorkspace();check(w.rows.length>=107,'브랜드 보존');check(w.rows.every(b=>['1순위','2순위','3순위'].includes(b.contactPriority)),'연락 순위');check(w.rows.filter(b=>b.contactPriority==='1순위').length===9,'기존 팜픽 분류');check(w.rows.some(b=>b.stock.consignment>0),'위탁 재고 유지');check(w.rows.some(b=>b.stock.unknown>0),'미분류 재고 유지');const p=crmPatch_({workflow:'매입 진행 확정'});check(!('거래방식'in p),'전환 상태와 기존 거래 분리');let fail=false;try{crmTermPatch_({trade:'위탁',state:'확정'})}catch(e){fail=true}check(fail,'확정 필수값');fail=false;try{crmTermPatch_({trade:'매입',state:'제안',price:'-1'})}catch(e){fail=true}check(fail,'음수 가격');check(crmTermPatch_({trade:'위탁',state:'제안',price:'12,000'})['공급가']==='12000','위탁 조건 지원');check(crmInventory_().length>0,'재고 연결');console.log(JSON.stringify({passed,brands:w.rows.length,consignmentBrands:w.rows.filter(b=>b.stock.consignment>0).length,notionWrites:0,inventoryWrites:0}));}

// Staff operations: source workbooks and a lightweight movement journal.
function opsSheet_(name,headers){const db=getDb_();let s=db.getSheetByName(name);if(!s){s=db.insertSheet(name);s.getRange(1,1,1,headers.length).setValues([headers]).setFontWeight('bold').setBackground('#e8edf4');s.setFrozenRows(1);}return s;}
function opsRows_(name){return crmRows_(name);}
function opsFiles_(code){return crmRows_(BOPS.SHEETS.FILES).filter(r=>r['브랜드코드']===code).map(r=>({'파일명':r['파일명'],'Drive주소':r['DriveURL'],'상태':r['상태'],'분류':r['분류']}));}
function opsSources_(code){return opsRows_('제출 상품자료').filter(r=>r['브랜드코드'].split(',').includes(code));}
function opsImportNext(){assertAdmin_();return withLock_(function(){const files=crmRows_(BOPS.SHEETS.FILES).filter(r=>/^DRIVE-/.test(r['파일ID'])&&/\.xlsx$/i.test(r['파일명'])),group={};files.forEach(r=>{const id=r['Drive파일ID'];if(!group[id])group[id]={id,name:r['파일명'],codes:[]};if(!group[id].codes.includes(r['브랜드코드']))group[id].codes.push(r['브랜드코드']);});const log=opsSheet_('제출자료 처리',['파일ID','파일명','시트수','자료행수','상태','처리일','비고']),done=opsRows_('제출자료 처리').filter(r=>r['상태']==='완료').map(r=>r['파일ID']),all=Object.values(group),file=all.find(f=>!done.includes(f.id));if(!file)return {done:true,total:all.length,completed:done.length};let converted;try{converted=Drive.Files.create({name:'_운영센터_자료확인_'+file.name,mimeType:MimeType.GOOGLE_SHEETS},DriveApp.getFileById(file.id).getBlob(),{fields:'id'});const book=SpreadsheetApp.openById(converted.id),sheets=book.getSheets(),target=opsSheet_('제출 상품자료',['자료ID','브랜드코드','파일ID','파일명','시트명','원본행','자료JSON','확인상태','상품명','원본URL']);const old=opsRows_('제출 상품자료').filter(r=>r['파일ID']===file.id);if(old.length)throw Error('부분 처리 자료가 있습니다. 재실행 전 확인이 필요합니다.');const out=[];sheets.forEach(sh=>{const v=sh.getDataRange().getDisplayValues();let header=[],nameCol=-1;v.forEach((row,i)=>{if(!row.some(x=>String(x).trim()))return;const h=row.map(x=>String(x).replace(/\s/g,''));const n=h.findIndex(x=>x==='상품명'||x==='제품명'||x==='제품명(원문)'||x==='옵션명');if(n>=0){header=row;nameCol=n;}const name=nameCol>=0&&header!==row?String(row[nameCol]||'').trim():'';out.push([file.id+'-'+sh.getSheetId()+'-'+(i+1),file.codes.join(','),file.id,file.name,sh.getName(),String(i+1),JSON.stringify({headers:header,values:row}).slice(0,49000),name?'제출 자료':'원본 정보',name,'https://drive.google.com/file/d/'+file.id+'/view']);});});if(out.length){const start=target.getLastRow()+1;if(start+out.length-1>target.getMaxRows())target.insertRowsAfter(target.getMaxRows(),start+out.length-1-target.getMaxRows());target.getRange(start,1,out.length,10).setNumberFormat('@').setValues(out.map(r=>r.map(crmSafeCell_)));}log.appendRow([file.id,file.name,sheets.length,out.length,'완료',now_(),'원본 파일 보존 · 발송재고는 입고 미처리']);return {done:done.length+1===all.length,total:all.length,completed:done.length+1,file:file.name,rows:out.length};}finally{if(converted&&converted.id)DriveApp.getFileById(converted.id).setTrashed(true);}});}
function opsJournal_(code){return opsRows_('간편 입출고').filter(r=>!code||r['브랜드코드']===code);}
function opsStock_(code){const base=crmInventory_().filter(r=>!code||r.brandCode===code).map(r=>Object.assign({},r));const products=crmAllProducts_(),map={};base.forEach(r=>map[r.productId+'|'+r.placeId]=r);opsJournal_(code).forEach(r=>{const key=r['상품ID']+'|'+r['장소ID'];let b=map[key];if(!b){const p=products.find(p=>p.productId===r['상품ID']);b={brandCode:r['브랜드코드'],productId:r['상품ID'],name:p?.productName||r['상품ID'],place:r['장소명'],placeId:r['장소ID'],purchase:0,consignment:0,unknown:0,sample:0,available:0};base.push(b);map[key]=b;}const field={'매입':'purchase','위탁':'consignment','미분류':'unknown'}[r['거래방식']]||'unknown';b[field]+=(r['구분']==='입고'?1:-1)*Number(r['수량']);b.available=b.purchase+b.consignment+b.unknown;b.updated=r['등록일'];});return base;}
function getSimpleOperations(){return crmReadScope_(()=>({products:crmAllProducts_().map(p=>({id:p.productId,brandCode:p.brandCode,name:crmText_(p.productName),barcode:p.barcode})),places:crmRows_('장소').filter(r=>r['장소ID']).map(r=>({id:r['장소ID'],name:r['장소명']||r['장소ID']})),journal:opsJournal_().slice(-100).reverse()}));}
function saveSimpleMovement(p){assertAdmin_();return withLock_(function(){if(!/^[a-zA-Z0-9-]{8,100}$/.test(p.requestId||''))throw Error('저장 요청을 새로 시작해 주세요.');const sh=opsSheet_('간편 입출고',['기록ID','브랜드코드','상품ID','장소ID','장소명','처리일','구분','수량','거래방식','비고','등록자','등록일','요청ID']);if(opsRows_('간편 입출고').some(r=>r['요청ID']===p.requestId))return {ok:true,duplicate:true};const product=crmAllProducts_().find(x=>x.productId===p.productId),place=crmRows_('장소').find(x=>x['장소ID']===p.placeId);if(!product||!place)throw Error('상품과 장소를 선택해 주세요.');if(!['입고','출고'].includes(p.type)||!['매입','위탁','미분류'].includes(p.trade))throw Error('입출고 구분을 확인해 주세요.');const q=Number(p.quantity);if(!Number.isSafeInteger(q)||q<=0||q>1000000)throw Error('수량은 1 이상 정수로 입력해 주세요.');crmValidateDate_(p.date);if(!p.date)throw Error('처리일을 입력해 주세요.');const b=opsStock_(product.brandCode).find(x=>x.productId===p.productId&&x.placeId===p.placeId),field={'매입':'purchase','위탁':'consignment','미분류':'unknown'}[p.trade];if(p.type==='출고'&&q>Number(b?.[field]||0))throw Error('선택한 장소의 '+p.trade+' 재고보다 출고량이 많습니다.');const row=[uuid_('MOV-'),product.brandCode,p.productId,p.placeId,place['장소명'],p.date,p.type,q,p.trade,String(p.memo||'').slice(0,4000),getActiveUserEmail_(),now_(),p.requestId];sh.getRange(sh.getLastRow()+1,1,1,row.length).setValues([row.map(crmSafeCell_)]);return {ok:true};});}

// Read scopes last for one request only; writes never reuse cached stock or versions.
function getBrandOverview(code){return crmReadScope_(function(){
 code=String(code||'');const row=crmAllBrands_().find(r=>r['브랜드ID']===code);if(!row)throw Error('브랜드를 찾을 수 없습니다.');
 const archive=crmRows_(BCRM.archive).filter(r=>r['브랜드ID']===code);
 return {brand:crmEnhance_(crmBrand_(row),row),activities:crmActivity_(code,archive,crmRows_(BCRM.notes)),issues:crmRows_('자료 확인사항').filter(r=>r['브랜드코드']===code&&r['상태']!=='완료'),products:[],files:[],archive:[],conditions:[],stock:[],movements:[],terms:[],submitted:[],link:null,stages:CRM_STAGES,samples:CRM_SAMPLES};
});}
function crmProductCards_(products){return products.map(p=>({id:p.productId,name:crmText_(p.productName),option:p.optionName,barcode:p.barcode,price:p.retailPrice,status:p.reviewStatus||p.status||'자료 수집',category:p.category,trade:p.tradeType,image:p.mainImageUrl||'',url:p.productUrl||p.detailPageUrl||'',purchase:p.purchasePrice||''}));}
function getBrandTab(code,tab){return crmReadScope_(function(){
 code=String(code||'');if(!crmAllBrands_().some(r=>r['브랜드ID']===code))throw Error('브랜드를 찾을 수 없습니다.');
 if(tab==='products'){
  const products=crmProductCards_(crmProducts_().filter(p=>p.brandCode===code));
  const latest={};crmRows_(BOPS.SHEETS.SUBMISSIONS).filter(r=>r['브랜드코드']===code).forEach(r=>latest[r['상품ID']||r['제출ID']]=r);
  const requests=Object.keys(latest).map(k=>latest[k]).map(r=>{let data={};try{data=JSON.parse(r['상품데이터JSON']||'{}')}catch(e){}return {submissionId:r['제출ID'],productId:r['상품ID'],status:r['상태'],updatedAt:r['수정일'],name:data.product_name||'',isChange:data._change_request===true};}).filter(r=>r.isChange&&r.status!==BOPS.STATUS.APPROVED);
  return {products:products,requests:requests};
 }
 if(tab==='terms'){const p=crmProducts_().filter(p=>p.brandCode===code),names={};p.forEach(x=>names[x.productId]=x.productName);return {products:crmProductCards_(p),terms:crmRows_('거래조건 관리').filter(r=>r['브랜드ID']===code).reverse(),conditions:crmRows_('가격·공급조건').filter(r=>Object.prototype.hasOwnProperty.call(names,r['상품ID'])).map(r=>Object.assign({},r,{'상품명':names[r['상품ID']]}))};}
 if(tab==='stock'||tab==='campaign'){const ids={};crmAllProducts_().filter(p=>p.brandCode===code).forEach(p=>ids[p.productId]=true);const d={stock:opsStock_(code),movements:crmRows_('재고거래').filter(r=>ids[r['상품ID']])};if(tab==='campaign'){d.products=crmProductCards_(crmProducts_().filter(p=>p.brandCode===code));d.link=listBrands_({query:code}).find(x=>x.brandCode===code)?.link||null;}return d;}
 if(tab==='archive')return {files:crmRows_(BCRM.attachments).filter(r=>r['브랜드ID']===code).concat(opsFiles_(code)),archive:crmRows_(BCRM.archive).filter(r=>r['브랜드ID']===code).map(r=>({id:r['자료ID'],type:r['구분'],title:r['제목'],url:r['원본URL'],body:r['본문'],properties:crmJson_(r['속성JSON']),importedAt:r['이관일']}))};
 if(tab==='profile')return {link:listBrands_({query:code}).find(x=>x.brandCode===code)?.link||null};
 throw Error('지원하지 않는 상세 탭입니다.');
});}
function getBrandSourcePage(code,page){assertAdmin_();code=String(code||'');page=Math.max(0,Math.floor(Number(page)||0));
 const sh=getDb_().getSheetByName('제출 상품자료');if(!sh||sh.getLastRow()<2)return {rows:[],page:0,total:0,pages:1};
 const headers=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],bc=headers.indexOf('브랜드코드'),nc=headers.indexOf('상품명');if(bc<0||nc<0)throw Error('제출자료 열을 확인해 주세요.');
 const count=sh.getLastRow()-1,codes=sh.getRange(2,bc+1,count,1).getDisplayValues(),names=sh.getRange(2,nc+1,count,1).getDisplayValues(),matches=[];
 codes.forEach((r,i)=>{if(String(r[0]).split(',').map(s=>s.trim()).includes(code)&&names[i][0])matches.push(i+2)});
 const pages=Math.max(1,Math.ceil(matches.length/25));page=Math.min(page,pages-1);const selected=matches.slice(page*25,page*25+25),runs=[];
 selected.forEach(row=>{const run=runs[runs.length-1];if(run&&run[0]+run[1]===row)run[1]++;else runs.push([row,1]);});
 const rows=[];runs.forEach(([start,length])=>sh.getRange(start,1,length,headers.length).getDisplayValues().forEach(v=>{const o={};headers.forEach((h,i)=>{if(h)o[h]=v[i]||''});rows.push(o)}));
 return {rows,page,total:matches.length,pages};
}
function testStaffPerformance(){const summary=getBrandWorkspace(),code=summary.rows.find(b=>b.productCount>100)?.brandCode||summary.rows[0].brandCode,t=Date.now(),light=getBrandOverview(code);if(light.products.length||light.submitted.length||light.stock.length)throw Error('개요에서 상세 자료를 미리 조회했습니다.');const products=getBrandTab(code,'products'),stock=getBrandTab(code,'stock'),full=getBrandDetail(code),source=getBrandSourcePage(code,0),moves=getSimpleOperations();if(JSON.stringify(products.products)!==JSON.stringify(full.products))throw Error('상품 조회 결과 불일치');if(JSON.stringify(stock.stock)!==JSON.stringify(full.stock))throw Error('재고 조회 결과 불일치');if(source.rows.length>25||source.total!==full.submitted.filter(r=>r['상품명']).length)throw Error('제출자료 페이지 불일치');if('stock'in moves||moves.journal.length>100)throw Error('입출고 불필요 조회');let invalid=false;try{getBrandTab(code,'invalid')}catch(e){invalid=true}if(!invalid)throw Error('탭 검증 실패');console.log(JSON.stringify({passed:6,brands:summary.rows.length,code,products:products.products.length,sourceTotal:source.total,sourcePage:source.rows.length,elapsedMs:Date.now()-t}));}
